;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Character.Enemy.Primary",NewTagName="Characters.Enemy.Primary")
+GameplayTagRedirects=(OldTagName="Character.Enemy",NewTagName="Characters.Enemy")
+GameplayTagRedirects=(OldTagName="Character.Player.Default",NewTagName="Characters.Player.Default")
+GameplayTagRedirects=(OldTagName="Character.Player.Melee.Brook",NewTagName="Characters.Player.Melee.Brook")
+GameplayTagRedirects=(OldTagName="Character.Player.Melee",NewTagName="Characters.Player.Melee")
+GameplayTagRedirects=(OldTagName="Character.Player.Ranged",NewTagName="Characters.Player.Ranged")
+GameplayTagRedirects=(OldTagName="Character.Player.Tank",NewTagName="Characters.Player.Tank")
+GameplayTagRedirects=(OldTagName="Character.Player",NewTagName="Characters.Player")
+GameplayTagRedirects=(OldTagName="Character",NewTagName="Characters")
+GameplayTagList=(Tag="Chacater.Player.AutoAttack",DevComment="")
+GameplayTagList=(Tag="Characters.Enemy.Primary",DevComment="")
+GameplayTagList=(Tag="Characters.Player.Default",DevComment="")
+GameplayTagList=(Tag="Characters.Player.Melee.Brook",DevComment="")
+GameplayTagList=(Tag="Characters.Player.Ranged",DevComment="")
+GameplayTagList=(Tag="Characters.Player.Ranged.Betisa",DevComment="")
+GameplayTagList=(Tag="Characters.Player.Tank",DevComment="")
+GameplayTagList=(Tag="Characters.Player.Tank.Vena",DevComment="")
+GameplayTagList=(Tag="Input.DynamicProjectileAbility",DevComment="")
+GameplayTagList=(Tag="Input.EAbility",DevComment="")
+GameplayTagList=(Tag="Input.QAbility",DevComment="")
+GameplayTagList=(Tag="Input.Test",DevComment="")
+GameplayTagList=(Tag="Projectile.Basic.Type1",DevComment="")
+GameplayTagList=(Tag="Projectile.Basic.Type2",DevComment="")

